### ISSUE TITLE
The version detail is not getting updated

### ISSUE THREAD

**Issue by mchavda-splunk** [splunk/addonfactory-ta-library-python#17]
The version detail is not getting updated in the `__init__.py` and `pyproject.toml` files

Files:
* https://github.com/splunk/addonfactory-ta-library-python/blob/main/splunktalib/__init__.py#L5
* https://github.com/splunk/addonfactory-ta-library-python/blob/main/pyproject.toml#L7

**Comment by arys-splunk** [comment]
Same as https://github.com/splunk/addonfactory-ucc-generator/issues/315
